import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import icon from "../public/chucknorris.png";
import Image from "next/image";
import moment from "moment";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ jokes }: any) {

  const { value, created_at } = jokes;

  return (
    <>
      <Head>
        <title>Random Jokes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={inter.className} key={jokes.id}>
          <div className={styles.grid}>
            <h1 className={inter.className}>Random Chuck Norris Jokes</h1>
            <Image height={70} width={70} src={icon} alt="chuk norises" />
          </div>
          <p className={styles.description}>{value}</p>
          <p style={{textAlign:'center', marginBottom:'13px'}}> <span style={{fontSize: '22px'}}>Created at :</span> {moment(`${created_at}`).format("MMMM Do YYYY hh:mm:ss")}</p>
        </div>
        <button onClick={()=>location.reload()} className={styles.button}>Next Joke</button>
      </main>
    </>
  );
}

// api link   https://api.chucknorris.io/jokes/random

export async function getStaticProps() {
  const res = await fetch(`https://api.chucknorris.io/jokes/random`);
  const jokes = await res.json();
  console.log(jokes);

  return {
    props: {
      jokes,
    },
  };
}
